<br />
<div class="entry-edit">
    <div class="entry-edit-head"><div class="ajax"><h4 class="icon-head head-customer-view"><?php echo Mage::helper('customernotes')->__('Customer Notes') ?></h4></div></div>
    <fieldset>
        <div>
            <?php if ($this->canAddNote()): ?>
                <div id="history_form" class="order-history-form">
                    <form method="POST" action="<?php echo $this->getSubmitAction(); ?>">
                        <?php echo $this->getBlockHtml('formkey') ?>
                        <input type="hidden" name="customer_id" value="<?php echo $this->getCustomerId(); ?>" />
                        <input type="hidden" name="customer_name" value="<?php echo $this->getCustomerName(); ?>" />
                        <span class="field-row">
                            <label class="normal" for="note"><?php echo Mage::helper('customernotes')->__('Disposition') ?></label>
                            <select name="contact_method">
                            
                            	<?php foreach(Mage::helper('customernotes')->getOptions() as $option) {
	                            	
	                            	echo "<option value=\"" . $option . "\">" . $option . "</option>";
                            	}
                            	?>
                            </select>
                            
                            <div class="f-right">
                            	<label class="normal" for="note"><?php echo Mage::helper('customernotes')->__('Campaign') ?></label>
                            	<select onchange="updateSteps();" name="campaign_id" id="campaign_id">
                            		<option value=""></option>
                            		<?php foreach(Mage::helper('customernotes')->getCampaigns() as $option) {
	                            	
	                            		echo "<option value=\"" . $option->getId() . "\">" . $option->getName() . "</option>";
									}
                            		?>
                            	</select>
                            </div>
                        </span>
                        <span class="field-row">
                        	 <div class="f-right">
                            	<select name="step_id" id="step_id">
                            		<option value="">Choose a Campaign</option>
                            	</select>	
							</div>
                        </span>
                        <span class="field-row">
                            <label class="normal" for="note"><?php echo Mage::helper('customernotes')->__('Note') ?></label>
                            <textarea name="note" rows="3" cols="5" style="height:6em; width:99%;" id="history_note"></textarea>
                        </span>
                        <div class="f-right">
                            <input type="submit" class="form-button" value="<?php echo Mage::helper('customernotes')->__('Add Note') ?>" />
                        </div>
                        <div class="clear"></div>
                    </form>	
                </div>
                <div class="divider"></div>
            <?php endif; ?>

            <ul class="note-list">

                <?php $notes = array_reverse($this->getNotes());
                foreach ($notes as $note):
                	//echo $note['note_id'];
                	$noteObj = Mage::getModel('customernotes/notes')->load($note['note_id']);
                	
                    ?>
                    <form method="POST" action="<?php echo $this->getDeleteAction(); ?>">
    <?php echo $this->getBlockHtml('formkey') ?>
                        <li>
                            <input type="hidden" name="customer_id" value="<?php echo $this->getCustomerId() ?>" />
                            <input type="hidden" name="note_id" value="<?php echo $note['note_id']; ?>" />
                            <strong><?php echo $this->helper('core')->formatDate($note['created_time'], 'medium') ?></strong>
                            <?php echo $this->helper('core')->formatTime($note['created_time'], 'medium') ?>
                             <span class="separator">|</span>
                             <?php if ($note['contact_method']): ?>
                             <strong><?php echo $note['contact_method']; ?></strong>
                             <span class="separator">|</span> 
                             <?php endif; ?>
    <strong><?php echo $note['username']; ?></strong>
                            <div class="f-right">
                            	<?php if ($noteObj->getCampaignId()) {
	                            	echo "<strong>" . $noteObj->getCampaign()->getName() . "</strong>";
	                            	if ($noteObj->getStep()) {
	                            		echo '<span class="separator">|</span> ';
										echo "<strong>" . $noteObj->getStep()->getName() . "</strong>";
	                            	}
                            	}
                            	?>
                                <!--input type="submit" class="form-button" value="<?php echo Mage::helper('customernotes')->__('Delete Note') ?>" onclick="return confirm('Are you sure you want to delete the note?')"/-->
                            </div>
                            <br/><?php echo $this->htmlEscape($note['note'], array('b', 'br', 'strong', 'i', 'u')) ?>
                        </li>
                    </form>
<?php endforeach; ?>

            </ul>
        </div>
    </fieldset>
</div>

<script>

	var steps = <?php echo Mage::helper('customernotes')->getJSONSteps(); ?>;
	var json = Object.toJSON( {"COUNTRIES":[{"COUNTRY":"Hong Kong","ID":1},{"COUNTRY":"Japan","ID":2}]} );
	
	function updateSteps() {
		//setDropDown($('step_id'),[]);
		//alert($('step_id').options.length);
		$('step_id').update('');
		if ($('campaign_id').value) {
			steps[$('campaign_id').value].forEach(function(entry) {
				$('step_id').options.add(new Option(entry.name, entry.id));
			});		
		} 
	
	}

	function setDropDown(field, data, method, index) {
	  field.options.length = index == null ? 1 : index;
	  data.each(
	    function(e) {
	      field.options.add(method(e));
	    }
	  );
	}
</script>
