<?php
/**
 * SoftwareMedia_Wizard extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       SoftwareMedia
 * @package        SoftwareMedia_Wizard
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Wizard view template
 *
 * @category    SoftwareMedia
 * @package     SoftwareMedia_Wizard
 * @author      Ultimate Module Creator
 */
?>
<?php $_wizard = $this->getCurrentWizard();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title wizard-title">
    <h1><?php echo $_wizard->getTitle(); ?></h1>
</div>
<div class="wizard-view">
    <?php if ($_wizard->getStaticBlock()): ?>
	<div class="wizard_static std">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($_wizard->getStaticBlock())->toHtml(); ?>
	</div>
	<?php endif; ?>
</div>

