<?php if ($this->canShowBlock()): ?>
    <div class="block block-layered-nav">
        <?php echo $this->getStateHtml() ?>
        <div class="block-content">
            <?php if ($this->canShowOptions()): ?>
                <p class="block-subtitle"><?php echo $this->__('Shopping Options') ?></p>
                <dl id="narrow-by-list">
                    <?php $_filters = $this->getFilters(); ?>
                    <?php foreach ($_filters as $_filter): ?>
                        <?php if ($_filter->getItemsCount() > 1): ?>
                            <?php   
			                $tmpTitle = $this->htmlEscape($this->__($_filter->getName()));
			                $tmpTitle = strtolower($tmpTitle);
			                $tmpTitle = preg_replace("/[\s]+/", "-", $tmpTitle);
			                $tmpTitle = str_replace("/", "-", $tmpTitle);
			                ?>
                                <?php if ($tmpTitle == 'category'): ?>            
			                <dt class="<?=$tmpTitle?>"><?php echo $this->__($_filter->getName()); ?></dt>
			                <dd class="<?=$tmpTitle?>"><?php echo $_filter->getHtml() ?></dd>
                                <?php endif; ?>
                                        
                        <?php endif; ?>
                    <?php endforeach; ?>
                                        
                    <?php foreach ($_filters as $_filter): ?>
                        <?php if ($_filter->getItemsCount() > 1): ?>
                            <?php   
			                $tmpTitle = $this->htmlEscape($this->__($_filter->getName()));
			                $tmpTitle = strtolower($tmpTitle);
			                $tmpTitle = preg_replace("/[\s]+/", "-", $tmpTitle);
			                $tmpTitle = str_replace("/", "-", $tmpTitle);
			                ?>
                                <?php if ($tmpTitle != 'category'): ?>            
			                <dt class="<?=$tmpTitle?>"><?php echo $this->__($_filter->getName()); ?></dt>
			                <dd class="<?=$tmpTitle?>"><?php echo $_filter->getHtml() ?></dd>
                                <?php endif; ?>
                                        
                        <?php endif; ?>
                    <?php endforeach; ?>                                        
                <script type="text/javascript">decorateDataList('narrow-by-list');</script>
                </dl>
            <?php endif; ?>
            <?php if ($this->getLayer()->getState()->getFilters()): ?>
                <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
