
<div class="footer-container">
    <div class="footer-block">
        <div class="footer-top">
            <a href="<?php echo $this->getUrl(); ?>shipping" class="free-shipping"><?php echo $this->__('Always free shipping') ?></a>
            <div class="footer-newsletter">
                <p class="text"><?php echo $this->__('GET EXCLUSIVE DEALS') ?></p>
                <div class="social-footer">
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('follow_us')->toHtml(); ?>
                </div>
                <div class="f-fix">
					<?php echo $this->getChildHtml('newsletter') ?>
                </div>
            </div>
        </div>
        <div class="footer-content">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_blocks')->toHtml(); ?>
        </div>
        <div class="footer-content footer-card">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_card')->toHtml(); ?>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/livechat.js') ?>"></script>

<p class="copyright"><label><?php echo $this->__('&copy; Copyright') ?> <?php echo date("Y") ?> - <?php echo $this->getCopyright() ?></label></p>

<!-- BEGIN LivePerson Monitor. -->
<script type="text/javascript">
	window.lpTag = window.lpTag || {};
	if (typeof window.lpTag._tagCount === 'undefined') {
		window.lpTag = {site: '8324495', section: lpTag.section || '', autoStart: lpTag.autoStart === false ? false : true, ovr: lpTag.ovr || {}, _v: '1.5.1', _tagCount: 1, protocol: location.protocol, events: {bind: function(app, ev, fn) {
					lpTag.defer(function() {
						lpTag.events.bind(app, ev, fn)
					}, 0)
				}, trigger: function(app, ev, json) {
					lpTag.defer(function() {
						lpTag.events.trigger(app, ev, json)
					}, 1)
				}}, defer: function(fn, fnType) {
				if (fnType == 0) {
					this._defB = this._defB || [];
					this._defB.push(fn)
				} else if (fnType == 1) {
					this._defT = this._defT || [];
					this._defT.push(fn)
				} else {
					this._defL = this._defL || [];
					this._defL.push(fn)
				}
			}, load: function(src, chr, id) {
				var t = this;
				setTimeout(function() {
					t._load(src, chr, id)
				}, 0)
			}, _load: function(src, chr, id) {
				var url = src;
				if (!src) {
					url = this.protocol + '//' + ((this.ovr && this.ovr.domain) ? this.ovr.domain : 'lptag.liveperson.net') + '/tag/tag.js?site=' + this.site
				}
				var s = document.createElement('script');
				s.setAttribute('charset', chr ? chr : 'UTF-8');
				if (id) {
					s.setAttribute('id', id)
				}
				s.setAttribute('src', url);
				document.getElementsByTagName('head').item(0).appendChild(s)
			}, init: function() {
				this._timing = this._timing || {};
				this._timing.start = (new Date()).getTime();
				var that = this;
				if (window.attachEvent) {
					window.attachEvent('onload', function() {
						that._domReady('domReady')
					})
				} else {
					window.addEventListener('DOMContentLoaded', function() {
						that._domReady('contReady')
					}, false);
					window.addEventListener('load', function() {
						that._domReady('domReady')
					}, false)
				}
				if (typeof (window._lptStop) == 'undefined') {
					this.load()
				}
			}, start: function() {
				this.autoStart = true
			}, _domReady: function(n) {
				if (!this.isDom) {
					this.isDom = true;
					this.events.trigger('LPT', 'DOM_READY', {t: n})
				}
				this._timing[n] = (new Date()).getTime()
			}, vars: lpTag.vars || [], dbs: lpTag.dbs || [], ctn: lpTag.ctn || [], sdes: lpTag.sdes || [], ev: lpTag.ev || []};
		lpTag.init()
	} else {
		window.lpTag._tagCount += 1
	}
</script>

<script type="text/javascript">
adroll_adv_id = "YAKH427VNFE3RIAJ44VLUJ";
adroll_pix_id = "D666DQIFWFHETOUK4WQNMI";
(function () {
var oldonload = window.onload;
window.onload = function(){
   __adroll_loaded=true;
   var scr = document.createElement("script");
   var host = (("https:" == document.location.protocol) ? "https://s.adroll.com" : "http://a.adroll.com");
   scr.setAttribute('async', 'true');
   scr.type = "text/javascript";
   scr.src = host + "/j/roundtrip.js";
   ((document.getElementsByTagName('head') || [null])[0] ||
    document.getElementsByTagName('script')[0].parentNode).appendChild(scr);
   if(oldonload){oldonload()}};
}());
</script>

<!-- END LivePerson Monitor. -->

<!-- BEGIN: Google Trusted Stores -->
<script type="text/javascript">
  var gts = gts || [];


  gts.push(["id", "571311"]);
  gts.push(["badge_position", "BOTTOM_LEFT"]);
  gts.push(["locale", "en_US"]);
  //gts.push(["google_base_offer_id", "ITEM_GOOGLE_SHOPPING_ID"]);
    <?php if (Mage::registry('current_product')) {
	  $prod = Mage::registry('current_product');
	  if ($prod->getAdminId()) 
	  	$base = $prod->getAdminId();
	  else
	  	$base = $prod->getSku();
	  	?>
	  	
	  gts.push(["google_base_offer_id", "<?php echo $base; ?>"]);
  <?php
  }
  ?>
  gts.push(["google_base_subaccount_id", "44232"]);
  //gts.push(["google_base_country", "ITEM_GOOGLE_SHOPPING_COUNTRY"]);
  //gts.push(["google_base_language", "ITEM_GOOGLE_SHOPPING_LANGUAGE"]);

  (function() {
    var gts = document.createElement("script");
    gts.type = "text/javascript";
    gts.async = true;
    gts.src = "https://www.googlecommerce.com/trustedstores/api/js";
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(gts, s);
  })();
</script>
<!-- END: Google Trusted Stores -->