
<div class="footer-container">
    <div class="footer-block">
        <div class="footer-top">
            <div class="footer-newsletter">
                <p class="text"><?php echo $this->__('GET EXCLUSIVE DEALS') ?></p>
                <div class="social-footer">
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('follow_us')->toHtml(); ?>
                </div>
                <div class="f-fix">
					<?php echo $this->getChildHtml('newsletter') ?>
                </div>
            </div>
        </div>
        <div class="footer-content">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_blocks')->toHtml(); ?>
        </div>
        <div class="footer-content footer-card">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_card')->toHtml(); ?>
        </div>
    </div>
</div>
<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//v2.zopim.com/?2r0YW0yB7jN8hskSvoq78q15oAkp7LCC';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->

<p class="copyright"><label><?php echo $this->__('&copy; Copyright') ?> <?php echo date("Y") ?> - <?php echo $this->getCopyright() ?></label></p>


<script type="text/javascript">
adroll_adv_id = "YAKH427VNFE3RIAJ44VLUJ";
adroll_pix_id = "D666DQIFWFHETOUK4WQNMI";
(function () {
var oldonload = window.onload;
window.onload = function(){
   __adroll_loaded=true;
   var scr = document.createElement("script");
   var host = (("https:" == document.location.protocol) ? "https://s.adroll.com" : "http://a.adroll.com");
   scr.setAttribute('async', 'true');
   scr.type = "text/javascript";
   scr.src = host + "/j/roundtrip.js";
   ((document.getElementsByTagName('head') || [null])[0] ||
    document.getElementsByTagName('script')[0].parentNode).appendChild(scr);
   if(oldonload){oldonload()}};
}());
</script>

<!-- END LivePerson Monitor. -->

<!-- BEGIN: Google Trusted Stores -->
<script type="text/javascript">
  var gts = gts || [];


  gts.push(["id", "571311"]);
  gts.push(["badge_position", "BOTTOM_LEFT"]);
  gts.push(["locale", "en_US"]);
  //gts.push(["google_base_offer_id", "ITEM_GOOGLE_SHOPPING_ID"]);
    <?php if (Mage::registry('current_product')) {
	  $prod = Mage::registry('current_product');
	  if ($prod->getAdminId()) 
	  	$base = $prod->getAdminId();
	  else
	  	$base = $prod->getSku();
	  	?>
	  	
	  gts.push(["google_base_offer_id", "<?php echo $base; ?>"]);
  <?php
  }
  ?>
  gts.push(["google_base_subaccount_id", "44232"]);
  //gts.push(["google_base_country", "ITEM_GOOGLE_SHOPPING_COUNTRY"]);
  //gts.push(["google_base_language", "ITEM_GOOGLE_SHOPPING_LANGUAGE"]);

  (function() {
    var gts = document.createElement("script");
    gts.type = "text/javascript";
    gts.async = true;
    gts.src = "https://www.googlecommerce.com/trustedstores/api/js";
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(gts, s);
  })();
</script>

<script>
  function updateStatus(s) {
    document.getElementById('live-chat-status').innerHTML = '<a href="javascript:$zopim.livechat.window.show()"><img src="/skin/frontend/enterprise/softwaremedia/images/chatnow.png" /></a>';
  }
 
  $zopim(function() {
    $zopim.livechat
      .setOnStatus(updateStatus);
  });
</script>

<!-- END: Google Trusted Stores -->
