<!-- Google Tag Manager -->
<?php if (strpos($_SERVER['REQUEST_URI'],'checkout/onepage/success')): ?>
<?php
    //Get Order Number & Order Total
    if (Mage::getSingleton('checkout/session')->getLastRealOrderId()):
    $order = Mage::getModel('sales/order')->loadByIncrementId(Mage::getSingleton('checkout/session')->getLastRealOrderId());
    $amount = number_format($order->getGrandTotal(),2,'.','');
    $shipping = number_format($order->getShippingAmount(),2,'.','');
    $tax = number_format($order->getTaxAmount(),2,'.','');
?>

<script>
dataLayer = [{
    'transactionId': '<?php echo Mage::getSingleton('checkout/session')->getLastRealOrderId(); ?>',
    'transactionAffiliation': 'SoftwareMedia',
    'transactionTotal': <?php echo $amount; ?>,
    'transactionTax': <?php echo $tax; ?>,
    'transactionShipping': <?php echo $shipping; ?>,
    'transactionProducts': [
    <?php 
    $items = $order->getAllItems();
    $itemcount=count($items);
    $count = 1;
    foreach($items as $item): ?>
    {
        'sku': '<?php echo $item->getSku(); ?>',
        'name': '<?php echo $item->getName(); ?>',
        'price': <?php echo number_format($item->getPrice(),2,'.',''); ?>,
        'quantity': <?php echo $item->getQtyToInvoice(); ?>
    }
    <?php
	    if ($count < $itemcount)
	    	echo ",";
	    	
	    $count++;
    endforeach;
    ?>
    ]
}];

</script>
<?php endif; ?>
<?php endif; ?>

<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-259L"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push(
{'gtm.start': new Date().getTime(),event:'gtm.js'}
);var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-259L');</script>
<!-- End Google Tag Manager -->