<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if ($this->getCollection()->getSize()): ?>
	<div class="toolbar">
		<?php if ($this->isExpanded()): ?>
			<div class="sort-by">
				<label><?php echo $this->__('Sort By') ?></label>
				<select onchange="setLocation(this.value)">
					<?php foreach ($this->getAvailableOrders() as $_key => $_order): ?>
						<?php if ($_order != 'Position') : // Remove "Position" from the sort option list ?>
							<option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if ($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
								<?php echo $_order ?>
							</option>
						<?php endif; // End for removing "Position" sort option ?>
					<?php endforeach; ?>
				</select>
				<?php if ($this->getCurrentDirection() == 'desc'): ?>
					<a href="<?php echo $this->getOrderUrl(null, 'asc') ?>"><img src="<?php echo $this->getSkinUrl('images/sort_desc_arrow.gif') ?>" alt="<?php echo $this->__('Set Ascending Direction') ?>" class="v-middle" /></a>
				<?php else: ?>
					<a href="<?php echo $this->getOrderUrl(null, 'desc') ?>"><img src="<?php echo $this->getSkinUrl('images/sort_asc_arrow.gif') ?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>
				<?php endif; ?>
			</div>
			<div class="sorter">
				<?php if ($this->isEnabledViewSwitcher()): ?>
					<p class="view-mode">
						<?php $_modes = $this->getModes(); ?>
						<?php if ($_modes && count($_modes) > 1): ?>
							<label><?php echo $this->__('View as') ?>:</label>
							<?php foreach ($this->getModes() as $_code => $_label): ?>
								<?php if ($this->isModeActive($_code)): ?>
									<strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>&nbsp;
								<?php else: ?>
									<a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>&nbsp;
								<?php endif; ?>
							<?php endforeach; ?>
						<?php endif; ?>
					</p>
				<?php endif; ?>

			</div>
		<?php endif; ?>
		<div class="pager">
			<p class="amount">
				<?php echo $this->__('Viewing %s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
			</p>
			<?php echo $this->getPagerHtml() ?>

		</div>
	</div>
	<?php



 endif ?>
