<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
	$_product = $this->getProduct();
?>
<?php if(!$_productCollection->getSize()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php
    $_helperCompare = $this->helper('catalog/product_compare');
    ?>    
    <div class="block-title">
        <button type="button" title="<?php echo $this->__('Compare') ?>" class="button" onclick="popWin('<?php echo $_helperCompare->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><span><span><?php echo $this->__('Compare') ?></span></span></button>
        <?php if ($_helperCompare->getItemCount() > 0): ?> 
            <small><?php echo $this->__('(%d)', $_helperCompare->getItemCount()) ?></small>
        <?php endif; ?>
    </div>    
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <?php $msrp = $_product->getMsrp(); ?>
    
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(335); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                 <div class="list-left">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <div class="platform">
						<?php if ($_product->getAttributeText('platform') == 'Mac'): ?>
							<img src="<?php echo $this->getSkinUrl(); ?>images/Mac-small.png" alt="Mac" />
						<?php endif; ?>
						<?php if ($_product->getAttributeText('platform') == 'Macintosh'): ?>
							<img src="<?php echo $this->getSkinUrl(); ?>images/Mac-small.png" alt="Mac" />
						<?php endif; ?>
						<?php if ($_product->getAttributeText('platform') == 'Windows'): ?>
							<img src="<?php echo $this->getSkinUrl(); ?>images/Windows-small.png" alt="Windows" />
						<?php endif; ?>
						<?php if ($_product->getAttributeText('platform') == 'PC'): ?>
							<img src="<?php echo $this->getSkinUrl(); ?>images/Windows-small.png" alt="Windows" />
						<?php endif; ?>
						<?php if ($_product->getAttributeText('platform') == 'PC Mac'): ?>
							<img src="<?php echo $this->getSkinUrl(); ?>images/Windows-small.png" alt="Windows" />
							<img src="<?php echo $this->getSkinUrl(); ?>images/Mac-small.png" alt="Mac" />
						<?php endif; ?>
                    </div>
                     <?php if ($_product->getResource()->getAttribute('product_type')): ?>
                    <div class="version">
                    	<?php echo $_product->getAttributeText('product_type'); ?>
                    </div>
                     <?php endif; ?>
                   
                    
                    <?php /*
                    <div class="desc std">
                        
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    */ ?>
                    <ul class="add-to-links">
                    	
                        <li>
                        	<?php if($_product->isSaleable()): ?>
                        	<span class="availability in-stock"><?php echo $this->__('<span>Availability:</span> In stock. Ships free today.') ?></span>
                            <?php else: ?>
                            <span class="availability out-of-stock"><?php echo $this->__('<span>Availability:</span> Out of stock') ?></span>
                            <?php endif; ?>
                        </li>
                        
                        <?php if ($_product->getData('manufacturer_pn_2')): ?>
                    	<li>
                    		<span><?php echo $this->__('Product #: '); ?></span>
							<?php echo $_product->getData('manufacturer_pn_2'); ?>
                    	</li>
                        <?php endif; ?>
                        
                        <?php /*
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="button link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        */ ?>
                        <li><?php if($_product->getRatingSummary()): ?>
	                    <?php 
                    	 $storeId    = Mage::app()->getStore()->getId();
					     $summaryData = Mage::getModel('review/review_summary')
					       ->setStoreId($storeId)
					       ->load($_product->getId());
					       if($summaryData->getRatingSummary()){
					       ?>
					       <div class="rating-box" style="float:left;">
					            <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
					       </div>
					       <?php 
					       }
					?>
	                    <?php endif; ?>
                        </li>
                        <li>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
		                    <div class="compare-img-list"><a href="<?php echo $_compareUrl ?>" title="Add To Compare" class="button link-compare"><?php echo $this->__('Compare') ?></a></div>
		                <?php endif; ?>
                        </li>
                    </ul>
                </div>
                
                    <div class="list-right">
	                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>">
	                        <?php echo $this->getPriceHtml($_product, true) ?>
	                    </a>	
	                    <?php if($msrp > $_product->getFinalPrice()):?>
						    <?php $_coreHelper = $this->helper('core');?>
						    <div class="product-msrp" style="text-align: right;font-weight: bold;">
						        <p style="font-size: 20px;" class=""><label><?php echo $this->__('MSRP: ') ?></label><span style="text-decoration: line-through;"><?php echo $_coreHelper->currency($msrp, true, false)?></span></p>
						        <?php if($msrp > $_product->getFinalPrice()):?>
						        <p style="font-size: 16px;font-weight: normal;">
						        	<?php if ((100-round(($_product->getFinalPrice()/$msrp) * 100 ,0)) > 0): ?>
						        		<?php echo $this->__('You Save: ') ?>
						        		<?php echo 100-round(($_product->getFinalPrice()/$msrp) * 100 ,0).'%';?>
						        	<?php endif; ?>
						        </p>
						        <?php endif;?>
						    </div>
						<?php endif;?>

	                    <?php if($_product->isSaleable()): ?>
	                       <button type="button" title="<?php echo $this->__('More Info') ?>" class="button btn-cart" onclick="setLocation('<?php echo $_product->getProductUrl();  ?>')"><span><span><?php echo $this->__('More Info') ?></span></span></button>
	                   <?php endif; ?>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = count($_productCollection); ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php $msrp = $_product->getMsrp(); ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(335); ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </a>
                <?php if($msrp > $_product->getFinalPrice()):?>
						    <?php $_coreHelper = $this->helper('core');?>
						    <div class="product-msrp" style="text-align: right;font-weight: bold;">
						        <p style="font-size: 20px;" class=""><label><?php echo $this->__('MSRP: ') ?></label><span style="text-decoration: line-through;"><?php echo $_coreHelper->currency($msrp, true, false)?></span></p>
						        <?php if($msrp > $_product->getFinalPrice()):?>
						        <p style="font-size: 16px;font-weight: normal;">
						        	<?php if ((100-round(($_product->getFinalPrice()/$msrp) * 100 ,0)) > 0): ?>
						        		<?php echo $this->__('You Save: ') ?>
						        		<?php echo 100-round(($_product->getFinalPrice()/$msrp) * 100 ,0).'%';?>
						        	<?php endif; ?>
						        </p>
						        <?php endif;?>
						    </div>
						<?php endif;?>
                
                <?php if($_product->getRatingSummary()): ?>
                   <?php 
                    	 $storeId    = Mage::app()->getStore()->getId();
					     $summaryData = Mage::getModel('review/review_summary')
					       ->setStoreId($storeId)
					       ->load($_product->getId());
					       if($summaryData->getRatingSummary()){
					       ?>
					       <div class="rating-box" style="float:left;">
					            <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
					       </div>
					       <?php 
					       }
					?>
                <?php endif; ?>                
                <div class="actions">
                	<?php /*
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    */?>
                    <ul class="add-to-links">
                    	<?php /*
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        */?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
		                    <div class="compare-img"><a href="<?php echo $_compareUrl ?>" title="Add To Compare" class="button link-compare"><?php echo $this->__('Add to Compare') ?></a></div>
		                <?php endif; ?>
                    </ul>
                </div>
            </li>
        <?php if (($i%$_columnCount==0) || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
       
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
