
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<?php $maxDisplayProduct = 5 ?>
<?php $imageWidth = 190; $imageHeight=208 ?>
<script type="text/javascript" language="javascript">
    jQuery(function() {
        jQuery('#product_new').carouFredSel({
            auto: false,
            scroll: 1,
            prev: '#prevProductNew',
            next: '#nextProductNew'
        });
    });
</script>
<div class="list_carousel">
    <ul id="product_new">
        <?php $i=0; foreach ($_products->getItems() as $_product): $i++; ?>
        <li>
            <div class="item slide <?php if(($i == $maxDisplayProduct && $_products->getSize() <= $maxDisplayProduct) || ($i == $_products->getSize())) echo 'last'?>">
                <?php include('view/labels.phtml')  ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imageWidth,$imageHeight) ?>" width="<?php echo $imageWidth ?>" height="<?php echo $imageHeight ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                    <div class="compare-img"><a href="<?php echo $_compareUrl ?>" title="Add To Compare" class="button link-compare"><?php echo $this->__('Add to Compare') ?></a></div>
                <?php endif; ?>
                <div class="new-description">
                    <h3><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>">
	                        <?php echo $this->getPriceHtml($_product, true) ?>
	                    </a>	
	                    <?php if($_product->getData('msrp')):?>
						    <?php $_coreHelper = $this->helper('core');?>
						    <div class="product-msrp" style="text-align: right;font-weight: bold;">
						        <p style="font-size: 16px;" class=""><label><?php echo $this->__('MSRP: ') ?></label><span style="text-decoration: line-through;"><?php echo $_coreHelper->currency($_product->getMsrp(), true, false)?></span></p>
						    </div>
						<?php endif;?>
                </div>
            </div>
        </li>
        <?php endforeach; ?>
    </ul>
    <a id="prevProductNew" class="prev-carousel">&lt;</a>
    <a id="nextProductNew" class="next-carousel">&gt;</a>
</div>
<?php endif;?>