<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<ul>
<li><div class="fb-like" data-href="http://www.facebook.com/SoftwareMedia" data-send="false" data-layout="box_count" data-width="450" data-show-faces="false" data-font="verdana">&nbsp;</div></li>

<li><a href="https://twitter.com/SoftwareMedia" class="twitter-share-button" data-url="http://www.softwaremedia.com" data-via="SoftwareMedia" data-lang="en" data-count="vertical">Tweet</a>
   <!--
 <a href="https://twitter.com/SoftwareMedia" class="twitter-follow-button" data-show-count="true" data-align="top" data-lang="en" data-show-screen-name="false">Tweet</a>

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
-->
</li>

<li><!-- <div class="g-plusone" data-size="tall" data-href="https://plus.google.com/103485723133992972837/posts"></div> -->



<!-- Place this tag where you want the +1 button to render. -->
<div class="g-plusone" data-size="tall" data-href="https://plus.google.com/103485723133992972837"></div>
</li>

<li class="last"><a href="//pinterest.com/pin/create/button/?url=http%3A%2F%2Fpinterest.com%2Fsoftwaremedia%2F&media=http%3A%2F%2Ffarm8.staticflickr.com%2F7027%2F6851755809_df5b2051c9_z.jpg&description=Next%20stop%3A%20Pinterest" data-pin-do="buttonPin" data-pin-config="above"><img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" /></a></li>

<li class="youtube"><a href="http://www.youtube.com/user/SoftwareMedia" target="_blank"><img src="<?php echo $this->getSkinUrl(); ?>images/YT-button.png" alt="YouTube" /></a></li>

</ul>


<script type="text/javascript">
(function(d){
  var f = d.getElementsByTagName('SCRIPT')[0], p = d.createElement('SCRIPT');
  p.type = 'text/javascript';
  p.async = true;
  p.src = '//assets.pinterest.com/js/pinit.js';
  f.parentNode.insertBefore(p, f);
}(document));
</script>

<? /*Script For Twitter */?>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<? /*Script For Google */?>
<!--
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
-->
<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>


