<?php 
$comments = $this->getAllCollection();
if(count($comments) >0):?>
<?php
$i =0;
foreach($comments as $comment):?>
<div class='<?php if($i % 2 == 0) echo "even"; else echo "odd"; ?>'>
    <?php echo $comment['message'] ?>
    <br/>
    <span><?php echo $comment['user_name'].", ".Mage::app()->getLocale()->date(strtotime($comment['date_post']), null, null, false)->toString('dd-MM-yyyy')?></span>
</div>
<?php $i +=1; ?>
<?php endforeach; ?>
<div id="testimonial_page">
    <?php echo $this->getChildHtml('toolbar.testimonial'); ?>    
</div>
<?php endif;?>
