<div class="page-title">
    <h1>Your Software Key Codes</h1>
</div>

	<?php 
	
	$order = $this->getOrder();
	$hasCodes = false;
	foreach ($order->getAllItems() as $item) {
		if ($item->getParentItemId())
			continue;
					
		if ($item->getQtyRefunded() == $item->getQtyInvoiced() && $item->getQtyInvoiced() > 0)
				continue;	
				
		if ($item->getSerialCodes()) 
			$hasCodes = true;		
	}
	?>
	
<div class="std">
	<?php if ($order->getId() && $hasCodes): ?>
	<p>Thank you for your recent order with SoftwareMedia.com! Your serial codes for order <?php echo $order->getIncrementId(); ?> are available below.</p>
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('serial_codes_issue')->toHtml(); ?>
	<br /><br />
	
	<table>
		<thead>
			<tr>
				<td width="75%">Product Name</td>
				<td width="25%">Codes</td>
			</tr>
		</thead>
		<tbody>
	<?php 
	$hasCodes = false;
	foreach ($order->getAllItems() as $item) {
		if ($item->getParentItemId())
				continue;

		if ($item->getQtyRefunded() == $item->getQtyInvoiced() && $item->getQtyInvoiced() > 0)
				continue;
				
		echo "<tr>";
		echo "<td>" . $item->getName();
		$additional = $this->getAdditional($item->getProductId()); 
		
		if ($additional) {
			echo " <a href='#' onclick='viewDetails(" . $item->getId() . ")'>(view details)</a>";
			echo "<table style='display: none; margin-top: 10px;' id='details" . $item->getId() . "'>";
			foreach($additional as $key=>$value) {
				if ($value == 'No' || $value == 'N/A')
					continue;
				echo "<tr><td style='background: #e8e8e8;'>" . $key. ": </td> <td>" . $value . "</td></tr>";
			}
			echo "</table>";
		}
		echo "</td>";
		
		if ($item->getSerialCodes()) {
			
					
			$hasCodes = true;
			if ($item->getSerialCodesViewed()) {
				echo "<td>" . nl2br($item->getSerialCodes()) . "</td>";
			} else {
				if ($item->getSerialCodesIssued() > 1)
					$suffix = "s"; 
				else
					$suffix = "";
					
				echo "<td><span id=\"code_" . $item->getId() . "\"\"><a href=\"#\" onclick=\"issueCode('" . $item->getId() . "','" . $item->getName() . "');\">Issue Code" . $suffix;
				if ($item->getSerialCodesIssued() > 0)
					echo " (" . $item->getSerialCodesIssued() . " available)";
					
				echo "</a></span></td>";
			} 
		} else {
			echo "<td>No Codes Available</td>";
		}
		echo "</tr>";
	}
	?>
		</tbody>
	</table>
	<?php else: ?>
		Error: Incorrect order, or no codes available. Please contact customer service.
	<?php endif; ?>
</div>

<script type="text/javascript">
	var unique = '<?php echo $this->getUnique(); ?>';
	function viewDetails(id) {
		$('details' + id).toggle();
	}
	function issueCode(itemId, title) {
		if (confirm('Are you sure? Issuing a key for "' + title + '" will make this item non-refundable.')) {
			new Ajax.Updater('code_' + itemId, '<?php echo Mage::helper("adminhtml")->getUrl('serialcodes/index/redeem'); ?>', {
			  method: 'get',
			  parameters: {item: itemId, unique: unique}
			});
		}
	}
</script>