<?php
$cant_use_points = (($this->getMinSpendablePoints() == $this->getMaxSpendablePoints()) && $this->getMinSpendablePoints() == 0);
?>

<?php if ($this->hasCartPointsData()): ?>
	<div class="discount-codes box rewards-box-spend-minicart discount">
		<div class="rewards-box-spend-header">
			<h2><?php echo $this->__('Spend your points'); ?></h2>
		</div>
		<div class="box-content">
			<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
				<span class="no_points_to_spend">
					<?php
					$msg = $this->__("You need to [[log-in]] to use your points.");
					echo str_replace("[[", "<a href='javascript:showLogIn()'>", str_replace("]]", "</a>", $msg));
					?>
					
				</span>
				<form action="<?php echo Mage::getUrl('customer/account/loginPost'); ?>" method="post" id="login-form" class="hidden">
								<?php echo $this->getBlockHtml('formkey'); ?>
								<input type="hidden" name="return_url" value="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>" />
								<div class="col1-set">
									<div class="col-1 registered-users">
										<div class="content">
											<ul class="spaced-list">
												<li>
													<label for="email" class="required padded"><em>*</em><?php echo $this->__('Email') ?></label>
													<input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="align-right input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
												</li>
												<li>
													<label for="pass" class="required padded"><em>*</em><?php echo $this->__('Password') ?></label>
													<input type="password" name="login[password]" class=" align-right input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
												</li>
											</ul>
											<p class="required"><?php echo $this->__('* Required Fields') ?></p>
										</div>
									</div>
								</div>
								<div class="col1-set">
									<div class="col-1 registered-users">
										<div class="buttons-set">
											<input type="hidden" name="referer" value="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>" />
											<button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
										</div>
									</div>
								</div>
							</form>
			<?php else: ?>
				<?php if ($this->showPointsSlider()): ?>
					<!-- Cart Slider -->
					<?php if ($this->hasNonDbpsCartRules()): ?>
						<h5 class="minicart-slider-header"><?php echo $this->__('Choose how many points to spend'); ?>: </h5>
					<?php endif; ?>
					<?php if ($this->customerHasUsablePoints() && !$cant_use_points): ?>
						<div class="cartSlider">
							<?php echo $this->getChildHtml('points_slider'); ?>
						</div>
						<input type="checkbox" name="use_all_points" id="use_all_points" onclick="toggleUseAllPoints(this.checked)"/>&nbsp;
						<label for="use_all_points"><?php echo $this->__('Maximize my discount with points'); ?></label>
					<?php else: ?>
						<?php if ($cant_use_points): ?>
							<span class="points_slider_msg">
								<?php
								echo "You have no points available to spend";								?></span>

							<form action="<?php echo Mage::getUrl('customer/account/loginPost'); ?>" method="post" id="login-form" class="hidden">
								<?php echo $this->getBlockHtml('formkey'); ?>
								<input type="hidden" name="return_url" value="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>" />
								<div class="col1-set">
									<div class="col-1 registered-users">
										<div class="content">
											<ul class="spaced-list">
												<li>
													<label for="email" class="required padded"><em>*</em><?php echo $this->__('Email') ?></label>
													<input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="align-right input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
												</li>
												<li>
													<label for="pass" class="required padded"><em>*</em><?php echo $this->__('Password') ?></label>
													<input type="password" name="login[password]" class=" align-right input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
												</li>
											</ul>
											<p class="required"><?php echo $this->__('* Required Fields') ?></p>
										</div>
									</div>
								</div>
								<div class="col1-set">
									<div class="col-1 registered-users">
										<div class="buttons-set">
											<input type="hidden" name="referer" value="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>" />
											<button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
										</div>
									</div>
								</div>
							</form>
						<?php elseif ($this->customerIsLoggedIn()): ?>
							<span class="no_points_to_spend"><?php echo $this->__("You don't currently have any points to spend."); ?></span>
						<?php else: ?>
							<span class="no_points_to_spend"><?php echo $this->__("You need to log-in to spend points."); ?></span>
						<?php endif; ?>
					<?php endif; ?>
				<?php endif; ?>

				<?php if ($this->hasNonDbpsCartRules()): /* has non "discount_by_points_spent" (slider) rules: */ ?>
					<!-- All other rules -->
					<?php $redemption_list = $this->collectShoppingCartRedemptions($this->getQuote()); ?>
					<div class="more-ways-to-spend <?php if ($this->showPointsSlider()): ?> more-ways-to-spend-also<?php endif; ?>" >
						<?php if ($this->showPointsSlider()): ?>
							<h5 class="more-ways-to-spend-header"><?php echo $this->__('More ways to spend points'); ?>: </h5>
						<?php endif; ?>
						<!-- Applied Rule Listing -->
						<?php foreach ($redemption_list['sorted_applied'] as $redemption): ?>
							<?php if ($redemption['is_dbps']) continue; ?>
							<div class="cart_redemption_item">
								<input type="checkbox" name="applied_cart_rule[]" id="applied_cart_rule[]"
									   value="<?php echo (string) $redemption['rule_id']; ?>" onclick="toggleCartRule(this)" checked="checked"/>&nbsp;
								<label for="applied_cart_rule[]">
									<?php if (isset($redemption['caption']) && !empty($redemption['caption'])): ?>
										<?php echo $redemption['caption']; ?>
									<?php else: ?>
										<?php echo $this->__('Spend <b>%s</b>, Get <b>%s</b>', $redemption['points_cost'], $redemption['action_str']) ?>
									<?php endif; ?>
								</label>
							</div>
						<?php endforeach; ?>

						<!-- Applicable Rule Listing -->
						<?php foreach ($redemption_list['sorted_applicable'] as $redemption): ?>
							<?php if ($redemption['is_dbps']) continue; ?>
							<div class="cart_redemption_item">
								<input type="checkbox" name="applicable_cart_rule[]" id="applicable_cart_rule[]"
									   value="<?php echo (string) $redemption['rule_id']; ?>" onclick="toggleCartRule(this)" />&nbsp;
								<label for="applicable_cart_rule[]">
									<?php if (isset($redemption['caption']) && !empty($redemption['caption'])): ?>
										<?php echo $redemption['caption']; ?>
									<?php else: ?>
										<?php echo $this->__('Spend <b>%s</b>, Get <b>%s</b>', $redemption['points_cost'], $redemption['action_str']) ?>
									<?php endif; ?>
								</label>
							</div>
						<?php endforeach; ?>
					</div>
				<?php endif; ?>
			<?php endif; ?>
		</div>
		<?php echo $this->getChildHtml('minicart_js'); ?>
	</div>
<?php endif; ?>