<script type="text/javascript">
    Event.observe(window, 'load', function() {
        ruleForm = new varienForm('rule_form', '<?php echo $this->getValidationUrl(); ?>');
        <?php if (is_null($this->getRequest()->getParam('rule'))): ?>
            MagentoBlockObj.hide('magento_block_listing_product_rules_hide','0');
        <?php endif; ?>
    });
</script>

<div class="entry-edit" id="magento_block_listing_product_rules">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Advanced Filter'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

                <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

                <?php echo $this->getChildHtml('rule_block') ?>

                <div style="margin-top: 15px">
                    <?php echo $this->getChildHtml('rule_filter_button') ?>
                </div>

            </form>

        </div>
    </div>

</div>