<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-account"><?php echo $this->__('Quote # %s', $quoteModel->getData('increment_id') ? $quoteModel->getData('increment_id') : $quoteModel->getData('quote_id')) ?>
		</h4>
	</div>
	<div class="fieldset">
		<table class="form-list" cellspacing="0">
			<tbody>
                <tr>
                    <td class="label"><label><?php echo $this->__('Last Update') ?></label></td>
                    <td class="value"><strong><?php echo $this->formatDate($quoteModel->getData('updated_at'), 'medium', true) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Quote Status') ?></label></td>
                    <td class="value">
                        <strong>
                            <span id="quote_status">
                                <?php
                                $substatus  = ($quoteModel->getData('substatus'))?$quoteModel->getData('substatus'):'';
                                $status     = Mage::getModel('qquoteadv/substatus')->getCurrentStatus($quoteModel->getData('status'), $substatus);
                                echo "<select name=\"status\">";
                                $disabled   = ($quoteModel->getData('status') == Ophirah_Qquoteadv_Model_Status::STATUS_PROPOSAL_SAVED)?'disabled':'';
                                foreach(Mage::getModel('qquoteadv/status')->getOptionArray(true) as $k=>$v):
                                    $selected=($status == $v)?"selected = selected":'';
                                    echo '<option value="'.$k .'" '.$selected.'>'.$v.'</option>';
                                endforeach;
                                echo '</select>';
                                ?>
                            </span>
                        </strong>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('RFQ From') ?></label></td>
                    <td class="value"><strong><?php echo $this->getStoreViewInfo($quoteModel->getData('store_id')); ?></strong></td>
                </tr>
            </tbody></table>
	</div>
</div>
