<?php if ($_products = Mage::getSingleton('Mage_Reports_Block_Product_Viewed')->getItemsCollection() && count($_products) > 0): ?>
<div class="sub-list">
    <h4 class="sub-list-label"><?php echo $this->__('Recently Viewed Items')?></h4>

    <ul>
        <?php foreach ($_products as $_product): ?>
        <li><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->stripTags($_product->getName(), null, true) ?></a> </li>
        <?php endforeach;?>
    </ul>
</div>
<?php endif;?>