<?php

$installer = $this;

$installer->startSetup();

$installer->run("

CREATE TABLE `ocm_fulfillment_synnex` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `trading_partner_code` varchar(255) NOT NULL DEFAULT '',
  `detail_record_id` varchar(255) NOT NULL DEFAULT '',
  `mfg_part_num` varchar(255) NOT NULL DEFAULT '',
  `synnex_internal_use` varchar(255) NOT NULL DEFAULT '',
  `synnex_sku` varchar(255) NOT NULL DEFAULT '',
  `status_code` varchar(255) NOT NULL DEFAULT '',
  `part_desc` varchar(255) NOT NULL DEFAULT '',
  `manufacturer_name` varchar(255) NOT NULL DEFAULT '',
  `synnex_internal_use2` varchar(255) NOT NULL DEFAULT '',
  `qty_on_hand_total` varchar(255) NOT NULL DEFAULT '',
  `synex_internal_use3` varchar(255) NOT NULL DEFAULT '',
  `contract_price` varchar(255) NOT NULL DEFAULT '',
  `msrp` varchar(255) NOT NULL DEFAULT '',
  `warehouse_qty_on_hand` varchar(255) NOT NULL DEFAULT '',
  `warehouse_qty_on_hand2` varchar(255) NOT NULL DEFAULT '',
  `returnable_flag` varchar(255) NOT NULL DEFAULT '',
  `warehouse_qty_on_hand3` varchar(255) NOT NULL DEFAULT '',
  `parcel_shippable` varchar(255) NOT NULL DEFAULT '',
  `warehouse_qty_on_hand4` varchar(255) NOT NULL DEFAULT '',
  `unit_cost` varchar(255) NOT NULL DEFAULT '',
  `warehouse_qty_on_hand5` varchar(255) NOT NULL DEFAULT '',
  `media_type` varchar(255) NOT NULL DEFAULT '',
  `warehouse_qty_on_hand6` varchar(255) NOT NULL DEFAULT '',
  `synnex_cat_code` varchar(255) NOT NULL DEFAULT '',
  `warehouse_qty_on_hand7` varchar(255) NOT NULL DEFAULT '',
  `synnex_internal_use4` varchar(255) NOT NULL DEFAULT '',
  `ship_weight` varchar(255) NOT NULL DEFAULT '',
  `serialized_flag` varchar(255) NOT NULL DEFAULT '',
  `warehouse_qty_on_hand8` varchar(255) NOT NULL DEFAULT '',
  `warehouse_qty_on_hand9` varchar(255) NOT NULL DEFAULT '',
  `synnex_reserved_use` varchar(255) NOT NULL DEFAULT '',
  `upc_code` varchar(255) NOT NULL DEFAULT '',
  `unspsc_code` varchar(255) NOT NULL DEFAULT '',
  `synnex_internal_use5` varchar(255) NOT NULL DEFAULT '',
  `sku_created_date` text NOT NULL,
  `one_source_flag` smallint(6) NOT NULL DEFAULT '0',
  `eta_date` datetime DEFAULT NULL,
  `abc_code` varchar(255) NOT NULL DEFAULT '',
  `kit_stand_alone_flag` varchar(255) NOT NULL DEFAULT '',
  `state_gov_price` varchar(255) NOT NULL DEFAULT '',
  `federal_gov_price` varchar(255) NOT NULL DEFAULT '',
  `educational_price` varchar(255) NOT NULL DEFAULT '',
  `taa_flag` varchar(255) NOT NULL DEFAULT '',
  `gsa_pricing` varchar(255) NOT NULL DEFAULT '',
  `promotion_flag` varchar(255) NOT NULL DEFAULT '',
  `promotion_comment` varchar(255) NOT NULL DEFAULT '',
  `promotion_expiration_date` varchar(255) NOT NULL DEFAULT '',
  `long_desc1` varchar(1000) NOT NULL DEFAULT '',
  `long_desc2` varchar(1000) NOT NULL DEFAULT '',
  `long_desc3` varchar(1000) NOT NULL DEFAULT '',
  `length_width_height` varchar(255) NOT NULL DEFAULT '',
  `synnex_reserved_use2` varchar(255) NOT NULL DEFAULT '',
  `gsa_nte_price` varchar(255) NOT NULL DEFAULT '',
  `platform_type` varchar(255) NOT NULL DEFAULT '',
  `product_description` varchar(255) NOT NULL DEFAULT '',
  `warehouse_qty_on_hand10` varchar(255) NOT NULL DEFAULT '',
  `warehouse_qty_on_hand11` varchar(255) NOT NULL DEFAULT '',
  `synnex_reserved_use3` varchar(255) NOT NULL DEFAULT '',
  `synnex_reserved_use4` varchar(255) NOT NULL DEFAULT '',
  `synnex_reserved_use5` varchar(255) NOT NULL DEFAULT '',
  `replacement_sku` varchar(255) NOT NULL DEFAULT '',
  `minimum_order_qty` varchar(255) NOT NULL DEFAULT '',
  `purchasing_requirements` varchar(255) NOT NULL DEFAULT '',
  `gov_class` varchar(255) NOT NULL DEFAULT '',
  `warehouse_qty_on_hand12` varchar(255) NOT NULL DEFAULT '',
  `mfg_drop_ship_warehouse_qty` varchar(255) NOT NULL DEFAULT '',
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ocm_fulfillment_ingram` (
  `fulfillment_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `change_code` varchar(255) NOT NULL DEFAULT '',
  `price_part_nbr` varchar(255) NOT NULL DEFAULT '',
  `price_vendor_nbr` varchar(255) NOT NULL DEFAULT '',
  `price_vendor_name` varchar(255) NOT NULL DEFAULT '',
  `price_desc1` varchar(255) NOT NULL DEFAULT '',
  `price_desc2` varchar(255) NOT NULL DEFAULT '',
  `price_retail` varchar(255) NOT NULL DEFAULT '',
  `price_vendor_part` varchar(255) NOT NULL DEFAULT '',
  `weight` varchar(255) NOT NULL DEFAULT '',
  `upc_code` varchar(255) NOT NULL DEFAULT '',
  `length` varchar(255) NOT NULL DEFAULT '',
  `width` varchar(255) NOT NULL DEFAULT '',
  `height` varchar(255) NOT NULL DEFAULT '',
  `cust_cost_c` varchar(255) NOT NULL DEFAULT '',
  `cust_cost` varchar(255) NOT NULL DEFAULT '',
  `product_key` varchar(255) NOT NULL DEFAULT '',
  `avail_stock_flag` varchar(255) NOT NULL DEFAULT '',
  `price_status` varchar(255) NOT NULL DEFAULT '',
  `new_cpu_code` varchar(255) NOT NULL DEFAULT '',
  `new_media` varchar(255) NOT NULL DEFAULT '',
  `new_cat_sub` varchar(255) NOT NULL DEFAULT '',
  `whse_has_stock_sw` varchar(255) NOT NULL DEFAULT '',
  `cost_rebate_appl_sw` varchar(255) NOT NULL DEFAULT '',
  `substitute_part` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`fulfillment_id`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

");

$installer->endSetup();
