<?php
/**
 * SoftwareMedia_Wizard extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       SoftwareMedia
 * @package        SoftwareMedia_Wizard
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Question children list template
 *
 * @category    SoftwareMedia
 * @package     SoftwareMedia_Wizard
 * @author      Ultimate Module Creator
 */
?>
<?php $_questions = $this->getQuestions(); ?>
<?php if ($_questions->getSize() > 0) :?>
    <div class="page-title question-title">
        <h2><?php echo $this->getCurrentQuestion()->getQuestion(); ?>:<?php echo $this->__('Children')?></h2>
    </div>
    <?php if ($this->_getDisplayMode() == 0) : ?>
        <div class="question-list-container">
            <?php foreach ($_questions as $_question) : ?>
                <div class="question-list-item">
                    <a href="<?php echo $_question->getQuestionUrl();?>" title="<?php echo $this->escapeHtml($_question->getQuestion()) ?>">
                        <?php echo $_question->getQuestion(); ?>
                    </a>
                </div>
            <?php endforeach;?>
        </div>
    <?php else : ?>
        <ul id="questions-list">
            <?php foreach ($_questions as $_question) : ?>
                <?php echo $this->drawQuestion($_question);?>
            <?php endforeach;?>
        </ul>
        <script type="text/javascript">
            wizardTree('questions-list');
        </script>
    <?php endif;?>
<?php endif;?>
